MightyLions/Cold_Pitch

src/main/java/com/ColdPitch/domain/entity/TimeEntity.java

[feat] base entity Added

---

.gitignore
src/main/java/com/ColdPitch/domain/entity/Comment.java
src/main/java/com/ColdPitch/domain/entity/TimeEntity.java
src/main/java/com/ColdPitch/domain/repository/CommentRepository.java
src/test/java/com/ColdPitch/domain/entity/comment/CommentTest.java

feat(comment): 댓글 추가, 수정 기능 추가

---

src/main/java/com/ColdPitch/domain/entity/Comment.java

1. 기능 추가
- Entity 추가
- 댓글 삽입
- 댓글 수정
2. 구조 수정
- @Setter, setter() 메소드로 변경

[Feature] 댓글 구조 수정 및 기능 추가

---

src/main/java/com/ColdPitch/domain/entity/Post.java
src/main/java/com/ColdPitch/domain/repository/PostRepository.java
src/test/java/com/ColdPitch/domain/entity/post/PostTest.java

close #2 게시글 도메인 추가
- Post(게시글) Entity 추가  
- Post Repository 추가
close #14
close #15 
close #16 
close #20
테스트코드 작성
- 게시글 생성, 삭제, 수정, 조회 테스트코드 작성

[Feature] 게시글 엔티티, 레포지토리 추가 및 CRUD 테스트코드 작성

---

src/main/java/com/ColdPitch/domain/entity/Post.java
src/main/java/com/ColdPitch/domain/entity/post/CurState.java
src/main/java/com/ColdPitch/domain/entity/post/PostState.java
src/test/java/com/ColdPitch/domain/entity/post/PostTest.java

- 게시글 엔티티 컬럼명 설정
- 게시글 상태를 저장하는 Enum 생성
- 테스트 코드 작성 close #19

[Feature] 게시글 상태 변경 기능 테스트코드 작성

---

build.gradle
src/main/java/com/ColdPitch/config/swagger/SwaggerConfig.java
src/main/java/com/ColdPitch/domain/apicontroller/HelloApiController.java
src/main/resources/application.yml

close #34 
core(swagger) : swagger setting

[Cors] swagger 세팅

---

src/main/java/com/ColdPitch/domain/entity/Tag.java
src/main/java/com/ColdPitch/domain/entity/tag/TagName.java
src/main/java/com/ColdPitch/domain/repository/TagRepository.java
src/test/java/com/ColdPitch/domain/entity/tag/TagTest.java
src/test/java/com/ColdPitch/domain/entity/user/UserTest.java

[Feature] tag엔티티 생성

---

src/test/java/com/ColdPitch/domain/entity/tag/TagTest.java
src/test/java/com/ColdPitch/domain/entity/user/UserTest.java

[Fix] 테스트코드 에러 수정

---

src/main/java/com/ColdPitch/domain/apicontroller/comment/CommentApiController.java
src/main/java/com/ColdPitch/domain/repository/CommentRepositoryCustom.java
src/main/java/com/ColdPitch/domain/repository/CommentRepositoryImpl.java
src/main/java/com/ColdPitch/domain/service/CommentService.java
src/test/java/com/ColdPitch/domain/repository/CommentRepositoryTest.java

userId를 기반으로 댓글을 조회하는 기능 추가
API Controller에서 주어진 갯수 만큼 더미 코멘트를 저장하는 API 추가

[Feature] 유저 id를 기반으로 댓글을 찾는 기능 및 더미 코멘트를 넣는 API 추가

---

src/main/java/com/ColdPitch/domain/entity/Dislike.java
src/main/java/com/ColdPitch/domain/entity/Like.java
src/main/java/com/ColdPitch/domain/repository/DislikeRepository.java
src/main/java/com/ColdPitch/domain/repository/LikeRepository.java
src/test/java/com/ColdPitch/domain/repository/PostRepositoryTest.java

- 게시글 테스트코드 수정
- 좋아요 엔티티 추가
- 싫어요 엔티티 추가
- 테스트 코드 없이 API개발로 나갈 예정

[Feature] 게시글 좋아요 싫어요 엔티티 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/TagApiController.java
src/main/java/com/ColdPitch/domain/service/TagService.java

태그 조회 및 생성 기능을 구현했습니다. 
close : #54

[Feature]  tag Api, 서비스 생성

---

build.gradle
src/main/java/com/ColdPitch/config/security/JwtConfig.java
src/main/java/com/ColdPitch/config/security/SecurityConfig.java
src/main/java/com/ColdPitch/domain/apicontroller/UserAuthApiController.java
src/main/java/com/ColdPitch/domain/entity/dto/jwt/RefreshToken.java
src/main/java/com/ColdPitch/domain/entity/dto/jwt/TokenDto.java
src/main/java/com/ColdPitch/domain/entity/dto/jwt/TokenRequestDto.java
src/main/java/com/ColdPitch/domain/entity/dto/user/LoginDto.java
src/main/java/com/ColdPitch/domain/repository/RefreshTokenRepository.java
src/main/java/com/ColdPitch/domain/repository/UserRepository.java
src/main/java/com/ColdPitch/domain/service/CustomUserDetailService.java
src/main/java/com/ColdPitch/domain/service/UserService.java
src/main/java/com/ColdPitch/jwt/JwtFilter.java
src/main/java/com/ColdPitch/jwt/SecurityUtil.java
src/main/java/com/ColdPitch/jwt/TokenProvider.java
src/main/java/com/ColdPitch/jwt/exception/JwtAccessDeniedHandler.java
src/main/java/com/ColdPitch/jwt/exception/JwtAuthenticationEntryPoint.java
src/test/java/com/ColdPitch/domain/apicontroller/UserAuthApiControllerTest.java
src/test/java/com/ColdPitch/domain/service/UserServiceTest.java

[Feature] 유저 로그인 부분생성 #50

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/entity/Post.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostRequestDto.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostResponseDto.java
src/main/java/com/ColdPitch/domain/entity/post/PostState.java
src/main/java/com/ColdPitch/domain/repository/UserRepository.java
src/main/java/com/ColdPitch/domain/service/PostService.java

[Feature] 게시글 작성 API 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostRequestDto.java
src/main/java/com/ColdPitch/domain/service/PostService.java
src/test/java/com/ColdPitch/domain/repository/PostRepositoryTest.java

- PostRequestDto에 수정 때 사용할 id값과 status값 추가
- 게시글 상태 변경 관련 API는 따로 생성할 예정
- update메서드는 Transactional 어노테이션을 활용하여 더티체킹을 사용

[Feature]: 게시글 수정 API 추가 #5

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/service/PostService.java

- 게시글 조회 API 생성
- Service단에 Dto변환 메서드 추가

feat(post): 게시글 조회 API 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/entity/post/PostState.java
src/main/java/com/ColdPitch/domain/repository/UserRepository.java
src/main/java/com/ColdPitch/domain/service/PostService.java

- 게시글 삭제 방식 변경 (데이터삭제 ->  상태변경) -> 게시글 상태 변경 API로 통합
- 로그인한 유저네임 대신 이메일을 사용

[Feature] 게시글 상태변경 API 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/UserAuthApiController.java
src/main/java/com/ColdPitch/domain/entity/dto/user/UserResponseDto.java
src/main/java/com/ColdPitch/domain/service/UserService.java
src/main/java/com/ColdPitch/utils/SecurityUtil.java
src/test/java/com/ColdPitch/domain/apicontroller/UserAuthApiControllerTest.java
src/test/java/com/ColdPitch/domain/service/UserServiceTest.java

**close #69** 
- 유저 더미데이터 생성
- 스웨거 default value 수정
- 서비스로직분리
- 더미데이터 생성 코드 추가 ( dummy data default UserType은 User이므로 User로 생성 원할시에는 그냥 두고 Admin원하는 경우만 ADMIN입력후 수정)
- security util 수정

[Refactor]  user dummy추가, user 서비스로직 분리 #69

---

src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/entity/User.java
src/main/java/com/ColdPitch/domain/repository/UserRepository.java
src/main/java/com/ColdPitch/domain/repository/UserRepositoryCustom.java
src/main/java/com/ColdPitch/domain/repository/UserRepositoryCustomImpl.java
src/main/java/com/ColdPitch/domain/service/UserService.java

close : #57 
- 유저 전체 조회 ( 이후에 ADMIN만 조회 가능하도록 수정할 수도 있음)
- 유저 본인 조회
- 유저 프로필 수정 ( 이름, 닉네임, 전화번호, 비밀번호 수정)

[Feature] user 수정부분, 전체조회, 본인 조회 API 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/entity/Post.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostResponseDto.java
src/main/java/com/ColdPitch/domain/entity/post/LikeState.java
src/main/java/com/ColdPitch/domain/repository/DislikeRepository.java
src/main/java/com/ColdPitch/domain/repository/LikeRepository.java
src/main/java/com/ColdPitch/domain/service/PostService.java

- Post 컨트롤러, 서비스 안에서 처리
- postState를 세 개로 나누어서 처리(Like, Dislike, Unselected)

[Feature] 게시굴 좋아요 싫어요 API 추가

---

build.gradle
src/main/java/com/ColdPitch/config/okHttp/OkHttpClientConfig.java
src/main/java/com/ColdPitch/config/security/JwtConfig.java
src/main/java/com/ColdPitch/domain/apicontroller/CompanyRegistrationController.java
src/main/java/com/ColdPitch/domain/entity/dto/companyRegistraion/CompanyRegistrationValidationDto.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationService.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationValidator.java

close : #33 
- 진위검증용 dto
- 진위 검증 로직
- 검증 및 저장 service
- controller

[Feature] company registration validator #33

---

src/main/java/com/ColdPitch/domain/service/CompanyRegistrationValidator.java
src/main/java/com/ColdPitch/utils/ServerUtil.java

- companyRegistrationValidator에서 요청 작성 시 현재 서버 URL을 동적으로 넣게끔 리팩토링

[Refactor] 현재 URL 동적으로 입력하도록 수정 #33

---

src/test/java/com/ColdPitch/domain/repository/PostRepositoryTest.java

- 카테고리를 String에서 Category타입으로 수정
- 유저 연결은 스웨거에서 테스트하는 걸로...

[Fix] 게시글 테스트코드 카테고리 수정 및 유저 삭제

---

build.gradle
src/main/java/com/ColdPitch/domain/apicontroller/CompanyRegistrationController.java
src/main/java/com/ColdPitch/domain/entity/dto/companyRegistraion/CompanyRegistrationDto.java

[Fix] swagger수정

---

build.gradle
src/main/java/com/ColdPitch/domain/apicontroller/CommentApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/CompanyRegistrationController.java
src/main/java/com/ColdPitch/domain/apicontroller/SolutionApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/TagApiController.java
src/main/java/com/ColdPitch/domain/entity/Post.java

refactor(controller): requestMapping에 /api/v1으로 변경
fix(post): M:1 관계를 casecade로 연관 매핑
fix(queryDSL): queryDSL 빌드 시 생성되는 경고를 해결하기 위한 의존관계 주입 (JSR305)

[Fix][Refactor] 구조 변경 및 버그사항 수정

---

build.gradle
src/main/java/com/ColdPitch/domain/apicontroller/CompanyRegistrationController.java
src/test/java/com/ColdPitch/domain/repository/SolutionRepositoryTest.java

fix(company): CompanyRegistrationController에서 경로 설정이 중복된 문제 수정
fix(jsr305): 의존관계 삭제
fix(solution): SolutionRepositoryTest에서 status 설정을 하지 않아 테스트에 실패하는 문제 수정

[Fix] QueryDSL 컴파일을 실패하는 문제 해결 및 기타 코드 수정

---

src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/UserAuthApiController.java
src/main/java/com/ColdPitch/domain/entity/CompanyRegistration.java
src/main/java/com/ColdPitch/domain/entity/User.java
src/main/java/com/ColdPitch/domain/entity/dto/user/CompanyRequestDto.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationService.java
src/main/java/com/ColdPitch/domain/service/UserService.java
src/test/java/com/ColdPitch/domain/apicontroller/UserAuthApiControllerTest.java
src/test/java/com/ColdPitch/domain/apicontroller/UserControllerTest.java
src/test/java/com/ColdPitch/domain/service/UserServiceTest.java

[Feature] 기업 회원 회원가입 추가#44

---

src/main/java/com/ColdPitch/domain/entity/CompanyRegistration.java
src/main/java/com/ColdPitch/domain/entity/dto/companyRegistraion/CompanyRegistrationDto.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationService.java

- CompanyRegistraion에 companyDescription 항목 추가
- CompanyRegistraionDto에 companyDescription 항목 추가
- CompanyRegistrationService단에서 dto로 받은 정보 builder()시  description도 같이 빌더할 수 있도록 수정

[Refactor] 기업 등록 시 기업 소개를 받고 저장할 수 있는 항목 추가 #99

---

src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/UserAuthApiController.java

[Refactor]  유저 정보 받아오는 방식 변경

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/entity/Post.java
src/main/java/com/ColdPitch/domain/entity/User.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostRequestDto.java
src/main/java/com/ColdPitch/domain/service/PostService.java
src/main/java/com/ColdPitch/domain/service/UserService.java

close #88 
- 유저-포스트 매핑
- 유저 작성 게시글 조회 기능

[Feature] 유저가 작성한 포스트 확인 기능 #88

---

src/main/java/com/ColdPitch/domain/apicontroller/CommentApiController.java
src/main/java/com/ColdPitch/domain/entity/comment/CommentRequestType.java
src/main/java/com/ColdPitch/domain/entity/dto/comment/CommentRequestDto.java
src/main/java/com/ColdPitch/domain/entity/dto/comment/CommentResponseDto.java
src/main/java/com/ColdPitch/domain/service/CommentService.java
src/main/java/com/ColdPitch/exception/handler/ErrorCode.java

[Feature] 댓글 Swagger API 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/CompanyRegistrationController.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationService.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationValidator.java
src/main/java/com/ColdPitch/exception/handler/ErrorCode.java

- ErrorCode에 CompanyRegistration 메시지 추가
- validateCompanyRegistrationService에 RuntimeException -> CustomException으로 변경
- Controller에 CustomException으로 변경

[Refactor] 사업자 등록 검증 exception 추가 및 수정 #122

---

src/main/java/com/ColdPitch/domain/apicontroller/UserTagController.java
src/main/java/com/ColdPitch/domain/entity/dto/user/CompanyResponseDto.java
src/main/java/com/ColdPitch/domain/entity/dto/user/UserResponseDto.java
src/main/java/com/ColdPitch/domain/entity/dto/usertag/TagRequestDto.java
src/main/java/com/ColdPitch/domain/repository/UserRepository.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationService.java
src/main/java/com/ColdPitch/domain/service/UserTagService.java
src/test/java/com/ColdPitch/domain/apicontroller/UserTagControllerTest.java
src/test/java/com/ColdPitch/domain/service/UserServiceTest.java
src/test/java/com/ColdPitch/domain/service/UserTagServiceTest.java

close #124 
- 유저 태그를 가지고 있는 회사를 찾아서 리턴한다.
- 테스트 코드(서비스)
- 기존의 기업회원 가입시의 API테스트를 모킹해서 테스트 처리
- 현재는 태그 입력시에 or 조회로 조회한다. 이후에 and기능 필요하면 추가

[Feature] 태그를 기반으로 기업 찾기 #124 

---

src/main/java/com/ColdPitch/domain/entity/Comment.java
src/main/java/com/ColdPitch/domain/repository/CommentRepositoryImpl.java

Refactor(comment): QueryDSL에서 pId로 리팩토링 되지 않았던 문제 수정, toString에서 제외되었던 필드 추가

[Refactor] Comment 리팩토링

---

src/main/java/com/ColdPitch/domain/apicontroller/CompanyRegistrationController.java
src/main/java/com/ColdPitch/domain/entity/CompanyRegistration.java
src/main/java/com/ColdPitch/domain/entity/dto/companyRegistraion/CompanyRegistrationDto.java
src/main/java/com/ColdPitch/domain/entity/dto/user/CompanyResponseDto.java
src/main/java/com/ColdPitch/domain/repository/CommentRepositoryImpl.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationService.java

사업자등록정보 진위확인 api 변경 사항
(https://www.data.go.kr/bbs/ntc/selectNotice.do?originId=NOTICE_0000000003116)
이에 따른 Request 양식  변경입니다.
- 기존의 CompanyAddress 부분을 모두 b_adr로 변경

[Refactor] 사업자 등록정보 진위검증 OpenApi Request 양식 변경에 따른 리팩토링 #130

---

src/main/java/com/ColdPitch/domain/apicontroller/PostApiController.java
src/main/java/com/ColdPitch/domain/entity/Dislike.java
src/main/java/com/ColdPitch/domain/entity/Like.java
src/main/java/com/ColdPitch/domain/entity/Post.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostRequestDto.java
src/main/java/com/ColdPitch/domain/entity/dto/post/PostResponseDto.java
src/main/java/com/ColdPitch/domain/service/PostService.java
src/main/java/com/ColdPitch/domain/service/UserService.java

- 좋아요, 싫어요 도메인 로직 추가
- 게시글에 사용하지 않는 boardId 삭제
- ResponseDto 빈 값 출력 제외
- PostService 설명 추가
close #141

[Feature] 게시글 리팩토링

---

src/main/java/com/ColdPitch/config/security/CorsConfig.java
src/main/java/com/ColdPitch/config/security/SecurityConfig.java
src/main/java/com/ColdPitch/exception/CustomSecurityException.java
src/main/java/com/ColdPitch/exception/ExceptionHandleFilter.java
src/main/java/com/ColdPitch/exception/handler/ErrorCode.java
src/main/java/com/ColdPitch/jwt/TokenProvider.java
src/main/java/com/ColdPitch/jwt/exception/JwtAccessDeniedHandler.java
src/main/java/com/ColdPitch/jwt/exception/JwtAuthenticationEntryPoint.java

close : #139 
- 필터 exception 처리 기능 추가
- 필터 기능 동작 확인

[Refactor] jwt 필터 기능 추가, exception

---

src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/repository/CommentRepository.java
src/main/java/com/ColdPitch/domain/repository/DislikeRepository.java
src/main/java/com/ColdPitch/domain/repository/LikeRepository.java
src/main/java/com/ColdPitch/domain/repository/PostRepository.java
src/main/java/com/ColdPitch/domain/service/PostService.java
src/main/java/com/ColdPitch/domain/service/UserService.java

close #140 
유저가 평가한 각 게시글을 하나씩 조회하는 방법에서 
-> postId를 모아서 한 번에 조회하는 방법으로 리팩토링

[Refactor] #140 유저가 평가한 게시글 조회 N+1 문제 해결

---

src/main/java/com/ColdPitch/config/okHttp/ApiConfig.java
src/main/java/com/ColdPitch/domain/service/CompanyRegistrationValidator.java

기존에 jwt config로 관리되던 API키를 분리하였습니다.
close #90

[Refactor] #90 API키 분리

---

src/main/java/com/ColdPitch/domain/apicontroller/CommentApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/entity/dto/user/UserRequestDto.java
src/main/java/com/ColdPitch/domain/repository/CommentRepository.java
src/main/java/com/ColdPitch/domain/repository/CommentRepositoryCustom.java
src/main/java/com/ColdPitch/domain/repository/CommentRepositoryImpl.java
src/main/java/com/ColdPitch/domain/service/CommentService.java
src/main/java/com/ColdPitch/domain/service/UserService.java
src/main/java/com/ColdPitch/exception/handler/ErrorCode.java
src/main/java/com/ColdPitch/exception/handler/ErrorResponse.java
src/test/java/com/ColdPitch/domain/repository/CommentRepositoryTest.java
src/test/java/com/ColdPitch/domain/service/UserServiceTest.java

Comment 관련 로직들 전반적으로 리팩토링
Error 코드 추가 및 status 값 추가
UserRequestDto에서 userType을 String에서 Enum으로 변경

Refactor (Comment, Error 코드, UserRequestDto 등) 리팩토링

---

src/main/java/com/ColdPitch/config/security/JwtConfig.java
src/main/java/com/ColdPitch/config/security/SecurityConfig.java
src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/apicontroller/UserAuthApiController.java
src/main/java/com/ColdPitch/domain/entity/dto/jwt/RefreshToken.java
src/main/java/com/ColdPitch/jwt/JwtFilter.java
src/main/java/com/ColdPitch/jwt/TokenProvider.java
src/test/java/com/ColdPitch/domain/apicontroller/UserAuthApiControllerTest.java
src/test/java/com/ColdPitch/domain/apicontroller/UserControllerTest.java
src/test/java/com/ColdPitch/domain/apicontroller/UserTagControllerTest.java
src/test/java/com/ColdPitch/domain/service/UserServiceTest.java
src/test/java/com/ColdPitch/domain/service/UserTagServiceTest.java

close #136 
- refresh tokne 헤더에 엑세스 토큰, 쿠키에 리프레시 토큰 read only로 수정하여 업로드
- 만료된 엑세스 토큰인 경우 필터에서 새로 만들어서 처리(RTR)
- 테스트 코드 일부 수정

[Refactor] #136 jwt 수정

---

src/main/java/com/ColdPitch/domain/entity/dto/sentiment/SentimentRequestDto.java
src/main/java/com/ColdPitch/domain/entity/dto/sentiment/SentimentResponseDto.java
src/main/java/com/ColdPitch/domain/service/SentimentService.java

- Sentiment Request Dto가 text로 했는데 오류나서 content로 바꿈

[Hotfix] #155 긍부정 분석 API 호출 Request 오류 수정

---

src/main/java/com/ColdPitch/config/cloud/S3Config.java
src/main/java/com/ColdPitch/core/manager/AWSFileManager.java
src/main/java/com/ColdPitch/core/manager/FileManager.java
src/main/java/com/ColdPitch/core/manager/UserFileManager.java
src/main/java/com/ColdPitch/domain/apicontroller/UserApiController.java
src/main/java/com/ColdPitch/domain/entity/User.java
src/main/java/com/ColdPitch/domain/service/UserService.java
src/main/java/com/ColdPitch/exception/handler/GlobalExceptionHandler.java
src/test/java/com/ColdPitch/domain/apicontroller/UserAuthApiControllerTest.java

close #158 
- 유저 이미지 파일 업로드 기능 추가
- 파일 이미지 업로드 전에 url 삭제 기능 추가 
- 유저 이미지 조회 url 기능 추가

[Feature] #158 유저 프로필 이미지 업로드 기능 추가

---

src/main/java/com/ColdPitch/domain/apicontroller/SentimentApiController.java
src/main/java/com/ColdPitch/domain/entity/dto/sentiment/SentimentClassifiedResponseDto.java
src/main/java/com/ColdPitch/domain/entity/dto/sentiment/SentimentLiteralStringRequestDto.java
src/main/java/com/ColdPitch/domain/service/SentimentApiClient.java
src/main/java/com/ColdPitch/domain/service/SentimentService.java
src/main/java/com/ColdPitch/exception/handler/ErrorCode.java
src/main/java/com/ColdPitch/exception/handler/GlobalExceptionHandler.java
src/main/java/com/ColdPitch/utils/ValueThenKeyComparator.java
src/test/java/com/ColdPitch/domain/service/SentimentServiceTest.java
src/test/java/com/ColdPitch/domain/service/WordAnalysisServiceTest.java

feat (Sentiment)
- SentimentService 긍정 부정 문자 빈도 리스트 리턴하는 메소드 추가
- SentimentApiController 추가
refactor (Sentiment)
- SentimentApiClient 예외상황 추가
- SentimentApi 에러코드 추가
refactor (Exception)
- @Validated 예외 상황 핸들러 추가

[Feat] 감정분석 및 워드 클라우드

---

src/test/java/com/ColdPitch/domain/apicontroller/UserAuthApiControllerTest.java
src/test/java/com/ColdPitch/domain/apicontroller/UserControllerTest.java
src/test/java/com/ColdPitch/domain/apicontroller/UserFileManagerTest.java
src/test/java/com/ColdPitch/domain/repository/UserRepositoryTest.java
src/test/java/com/ColdPitch/domain/service/UserTagServiceTest.java

close #172 
s3 모킹 테스트 진행
현재 service에 모킹된 파일 매니저를 추가하는걸로 진행했습니다
추후에 s3 userfilemanager 테스트 환경에서 다르게 모킹할 수 있도록 진행하겠습니다

[Test] #172 s3 모킹 테스트 수정
